### ISSUE TITLE
allow to configure a remote salt-api end point

### ISSUE THREAD

**Issue by bbinet** [martinhoefling/molten#21]
If we want to serve this web application locally and connect to a remote salt-api instance.

This would be used similarly to the https://github.com/saltstack/pepper command line tool.

**Comment by bbinet** [comment]
In `config.js`, I tried to set `API_BASE_URL` to the full url of my salt-api instance but I can't login anymore: I get the error `Origin is not allowed by Access-Control-Allow-Origin`

**Comment by martinhoefling** [comment]
Same origin policy in browsers can be a bit tricky. It's actually not something molten can fix itself...

Instead of serving molten directly from salt-api, you could proxy salt-api on your server such that requests are answered from the same origin from the browser point of view.
Something as described here should work:
http://oskarhane.com/avoid-cors-with-nginx-proxy_pass/

Salt-api also has CORS preflight request support. However, I am not sure what its actual status is https://github.com/saltstack/salt/issues/14058.

**Comment by bbinet** [comment]
I tried to configure a nginx proxy, but it does not work for me.
Do you know how CORS preflight is supposed to work? Do I need to configure something in the salt-master config file?

**Comment by martinhoefling** [comment]
I quickly tried it out myself and it seems as if salt does not send the correct answer on OPTIONS requests. To me, it seems as if #14058 is still not fully resolved. I am closing the issue since it is not clear to me how molten could solve the actual issue. Feel free to reopen, if there's a suggestion how to fix it.

@bbinet can you post a gist with your nginx config and setup details, log messages etc.? Maybe I find the error in your nginx proxy setup.

**Comment by bbinet** [comment]
thanks @martinhoefling but finally I will run molten UI directly from the salt-api, it will be easier.

**Comment by martinhoefling** [comment]
@bbinet: I fixed the salt-api bug and created a pull request: https://github.com/saltstack/salt/pull/27826
Should be possible with future versions of salt.

**Comment by bbinet** [comment]
Thanks @martinhoefling.
I've monkey patched my salt-master with your fix, and when I log in molten I don't have the error `Origin is not allowed by Access-Control-Allow-Origin` anymore, but I'm not able to see any minion or run any command in the molten interface.
On the salt-master side, the only log that I get is "Clear payload received with command mk_token" when I log in molten, but nothing else.
Any idea about what is wrong? and how to give you more debug info?

**Comment by martinhoefling** [comment]
I noticed, that there's some error routing to the login route. I'll investigate that. Can you opens separate issue with your configuration details?
